apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-26899
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-26899
  template:
    metadata:
      labels:
        app: webapp-26899
    spec:
      serviceAccountName: webapp-sa-26899
      containers:
        - name: webapp-container-26899
          image: akashpandiyan/webapp-assessment-26899:v5
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: webapp-config-26899
            - secretRef:
                name: webapp-secret-26899
          volumeMounts:
            - name: webapp-storage-26899
              mountPath: /usr/share/webapp-26899
      volumes:
        - name: webapp-storage-26899
          persistentVolumeClaim:
            claimName: webapp-pvc-26899
